# Generated by Django 3.0.1 on 2019-12-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20191224_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
