# Generated by Django 3.0.1 on 2019-12-24 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20191224_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublesson',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Quiz'),
        ),
    ]
