# Generated by Django 3.0.1 on 2019-12-27 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20191226_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sublesson',
            name='quiz',
        ),
        migrations.AddField(
            model_name='quiz',
            name='sublesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.SubLesson'),
        ),
    ]
